[package]
name = "nizziel"
version = "0.1.0"
authors = ["liabri"]
edition = "2021"

[lib]
name = "nizziel"
path = "src/lib.rs"
crate-type = ["rlib"]

[dependencies]
reqwest = { version = "0.11.9", features = ["blocking"] }
zip = "0.5"
futures = "0.3.12"